version: '3.4'

services:
  web:
    image: slack
    build:
      context: web
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 3000:5000
  graphql:
    image: graphql
    build:
      context: graphql
      dockerfile: ./Dockerfile
    ports:
        - 4000:4000
  postgres:
    image: postgres:12-alpine
  redis:
    image: redis:5-alpine