version: '3.4'

services:
  graphql:
    image: graphql
    build:
      context: graphql
      dockerfile: ./Dockerfile
    env_file:
      - .env.example
    ports:
        - 4000:4000
  postgres:
    image: postgres:12-alpine
    environment:
      POSTGRES_PASSWORD: x2f04naR2SUD17WGfo12cg==
      POSTGRES_DB: slack
      POSTGRES_USER: postgres
  redis:
    image: redis:5-alpine